package com.ccunix.ihousekeeping.basedb.dao;
import java.util.List;

import com.ccunix.ihousekeeping.base.util.DataSourceType;
import com.ccunix.ihousekeeping.basedb.domain.T_s_advertisement_manager;
@DataSourceType(DataSourceType.main)public interface T_s_advertisement_manager_Dao_Iface {
public void insert_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
public void update_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
public void delete_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
public List queryAll_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
public List queryBy_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
}
