package com.ccunix.ihousekeeping.basedb.service;
import com.ccunix.ihousekeeping.basedb.domain.T_s_user_manager_role;
import java.util.List;
public interface T_s_user_manager_role_Service_Iface {
public void insert_t_s_user_manager_role(T_s_user_manager_role t_s_user_manager_role) throws Exception;
public void update_t_s_user_manager_role(T_s_user_manager_role t_s_user_manager_role) throws Exception;
public void delete_t_s_user_manager_role(T_s_user_manager_role t_s_user_manager_role) throws Exception;
public List queryAll_t_s_user_manager_role(T_s_user_manager_role t_s_user_manager_role) throws Exception;
public List queryBy_t_s_user_manager_role(T_s_user_manager_role t_s_user_manager_role) throws Exception;
}
