package com.ccunix.ihousekeeping.basedb.service;
import com.ccunix.ihousekeeping.basedb.domain.T_s_advertisement_manager;
import java.util.List;
public interface T_s_advertisement_manager_Service_Iface {
public void insert_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
public void update_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
public void delete_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
public List queryAll_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
public List queryBy_t_s_advertisement_manager(T_s_advertisement_manager t_s_advertisement_manager) throws Exception;
}
